name: deploy
on:
  workflow_dispatch:
jobs:
  semantic-release:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    steps:
      - id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
